version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    hostname: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=catalogdb
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_catalog

  catalog-service:
    image: natal/catalog-service:1.0
    ports:
      - "8084:8084"
    container_name: catalog_service
    depends_on:
      - postgres
