version: '3'
services:
  postgres-catalog:
    image: postgres:9.6-alpine
    hostname: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=catalogdb
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_catalog